good_xml_response: >
  <result>
    <mediaId>321</mediaId>
    <source>some_source</source>
    <status>done_done</status>
    <description>funky done description</description>
    <format>
      <output>3DG</output>
      <destination>coolplace</destination>
      <destination_status>SAVED</destination_status>
    </format>
  </result>

bad_xml_response: >
  <result>
    <mediaId>321</mediaId>
    <source>some_source</source>
    <status>Error</status>
    <description>funky done description</description>
    <format>
      <output>3DG</output>
      <destination>coolplace</destination>
      <destination_status>
          Error (All your ships we have)
      </destination_status>
      <suggestion>Buy more ships to find</suggestion>
    </format>
  </result>

